### ISSUE TITLE
Hook into the docker event stream

### ISSUE THREAD

**Issue by binocarlos** [ClusterHQ/powerstrip#38]
If powerstrip listened to the docker event stream - it means adapters could be configured to be told when a container dies (or any other event that is not the result of a docker HTTP api call).

The `adapters.yml` would need another section - something like `events` perhaps:

``` yaml
version: 1
endpoints:
  "POST /*/containers/create":
    pre: [weave]
    post: [weave]
events:
   die: [weave]
adapters:
  weave: http://weave/weave-adapter
```

The payload could be something like:

```
POST /adapter HTTP/1.1
Content-type: application/json
Content-length: ...

{
    PowerstripProtocolVersion: 1,
    Type: "event",
    Event: {
        Type: "DIE",
        Body: "{ ... }" or null
    }
}
```

The main point is to allow adapters to know that a container has died on its own rather than as a result of a HTTP request generated by the docker client.

Just something that cropped up in my head - it might be out of the scope of powerstrip not sure?
