### ISSUE TITLE
Powerstrip not work with go-dockerclient?

### ISSUE THREAD

**Issue by WIZARD-CXY** [ClusterHQ/powerstrip#65]
I am using powerstrip socketplane and slowreq adapter . But I found that it works with cli command like `docker run ...` , But not working with fsouza/go-dockerclient.I debug a little and found nothing.Does anyone knows why?? Many thanks!

**Comment by binocarlos** [comment]
Hi - do you get an error message of any kind?

How are you configuring the go-dockerclient to speak to powerstrip?  Powerstrip does not speak TLS for example.

As much info as you can provide would be cool :-)

**Comment by WIZARD-CXY** [comment]
I use `http://127.0.0.1:2375` as the docker endpoint when I create a new go-dockerclient, when I use this client to create and run a container, the adapter saw no incoming message as if there is no /adapter request.I have no idea of  twisted framework.The socketplane adapter.yaml is as follows
`
version: 1
endpoints:
  "POST /*/containers/create":
    pre: [socketplane]
  "POST /*/containers/*/start":
    post: [socketplane]
  "DELETE /*/containers/*":
    post: [socketplane]
adapters:
  socketplane: http://localhost:6675/adapter
`

**Comment by binocarlos** [comment]
Thanks - so basically we think that the socketplane adapter is never getting the request.

So - when you do a `docker run` cli command - it does 2 HTTP requests:

 * POST /containers/create
 * POST /containers/xxxxx/start

I'm assuming that in your code - you have 2 calls to mirror this (looking at the [docs](http://godoc.org/github.com/fsouza/go-dockerclient)):

 * [CreateContainer](http://godoc.org/github.com/fsouza/go-dockerclient#Client.CreateContainer)
 * [StartContainer](http://godoc.org/github.com/fsouza/go-dockerclient#Client.StartContainer)

Do you get any kind of HTTP error response back from the Powerstrip server or does it just hang?

Also - I notice you mention `adapters.yaml` not `adapters.yml` - are you **sure** that the Powerstrip server is picking up the correct config file?

There is nothing obvious and I've never used this go library so I'm kind of stabbing in the dark I'm afraid.

**Comment by binocarlos** [comment]
One other thing - I notice that the socketplane adapter is configured to speak to `localhost` from the config:

```yaml
socketplane: http://localhost:6675/adapter
```

So is the socketplane adapter running in a container?   Powerstrip runs inside a container and so localhost from inside the container will not point at the host.

Try doing an `ifconfig` on the host and grabbing the IP address of `eth0` - try replacing `localhost` with this IP address and restarting Powerstrip to see if this makes a difference.

Or - you can try running the SocketPlane adapter in a container (if it will) and using something like `--link socketplane:socketplane` and then `socketplane: http://socketplane:6675/adapter`

**Comment by WIZARD-CXY** [comment]
I debug some time and found that when I use docker cli command the actual request is 
POST   /v1.7/containers/create and POST /v1.17/containers/xxxxx/start.
But the go-dockerclient is just 
POST /containers/create
POST /containers/xxxxx/start
without version info.Is it a reason why it isn't working?
I am sure that powerstrip select the right yaml config file, or the docker cli won't work either you know.
and socketplane is also correctly running.
In fact the socketplane container is usingthe  host network mode,so It can be easily accessed

**Comment by binocarlos** [comment]
Ahh OK - perhaps it is a small error in the way Powerstrip is routing - thanks for debugging this :-)

What happens if you change the adapters.yml to be:

```yaml
version: 1
endpoints:
  "POST /containers/create":
    pre: [socketplane]
  "POST /containers/*/start":
    post: [socketplane]
  "DELETE /*/containers/*":
    post: [socketplane]
adapters:
  socketplane: http://localhost:6675/adapter
```

The idea being that perhaps the initial `/*` is confusing the Powerstrip routing?

Can you give that a try and report back (thanks again)

**Comment by WIZARD-CXY** [comment]
I tried as you said before , but there is other error reported. It is kind of container inspect error.I am really confused.

**Comment by WIZARD-CXY** [comment]
And if I change it without no version info, will the docker cli run fail?

**Comment by binocarlos** [comment]
Hmmm - we can always add 2 routes to get around using the docker cli & the go-lang client...

The main issue is why the go-lang client is not working...  So - with the route set to `/containers/create` you are saying there is a container inspect error?  Can you post it...

I am equally confused as to what is causing this :-)

**Comment by WIZARD-CXY** [comment]
I will post it tomorrow morning because it's in my lab.Now I assumed there is some error in socketplane part. Because it need to inspect a running container and configure the network for it and tomorrow I will debug deeper.

**Comment by binocarlos** [comment]
thanks - its appreciated :-)

**Comment by WIZARD-CXY** [comment]
After the changing , I got the request which powerstrip passed to socketplane adapter.The socketplane "PostHook" seems a little buggy and can't find the correct docker containerID, I will do a patch and maybe a pr to socketplane.
BTW, I want the both the docker command and dockerclient work with powerstrip. How can I achieve that?

**Comment by binocarlos** [comment]
Hey - well done for getting the request to the adapter :-)

So - for the moment, the best way to get requests from both the docker cli and golang client is to duplicate routes in the adapters.yml - less than ideal but it "should" work (tm)

```yaml
version: 1
endpoints:
  "POST /containers/create":
    pre: [socketplane]
  "POST /*/containers/create":
    pre: [socketplane]
  "POST /containers/*/start":
    post: [socketplane]
  "POST /*/containers/*/start":
    post: [socketplane]
  "DELETE /containers/*":
    post: [socketplane]
  "DELETE /*/containers/*":
    post: [socketplane]
adapters:
  socketplane: http://localhost:6675/adapter
```
